<?php
/**
 * UnitsApi
 * PHP version 5
 *
 * @category Class
 * @package  Kaufland\Seller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * OpenAPI spec version: 2.13.1
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Kaufland\Seller\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Kaufland\Seller\ApiException;
use Kaufland\Seller\Configuration;
use Kaufland\Seller\HeaderSelector;
use Kaufland\Seller\ObjectSerializer;

/**
 * UnitsApi Class Doc Comment
 *
 * @category Class
 * @package  Kaufland\Seller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class UnitsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation bulkUpdateUnits
     *
     * Update some fields of a given set of units
     *
     * @param  \Kaufland\Seller\Model\UnitsBulkUpdateRequest[] $body Update Object (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     *
     * @throws \Kaufland\Seller\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Kaufland\Seller\Model\UnitsBulkUpdateResponse
     */
    public function bulkUpdateUnits($body, $storefront)
    {
        list($response) = $this->bulkUpdateUnitsWithHttpInfo($body, $storefront);
        return $response;
    }

    /**
     * Operation bulkUpdateUnitsWithHttpInfo
     *
     * Update some fields of a given set of units
     *
     * @param  \Kaufland\Seller\Model\UnitsBulkUpdateRequest[] $body Update Object (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     *
     * @throws \Kaufland\Seller\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Kaufland\Seller\Model\UnitsBulkUpdateResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function bulkUpdateUnitsWithHttpInfo($body, $storefront)
    {
        $returnType = '\Kaufland\Seller\Model\UnitsBulkUpdateResponse';
        $request = $this->bulkUpdateUnitsRequest($body, $storefront);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 207:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\UnitsBulkUpdateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation bulkUpdateUnitsAsync
     *
     * Update some fields of a given set of units
     *
     * @param  \Kaufland\Seller\Model\UnitsBulkUpdateRequest[] $body Update Object (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bulkUpdateUnitsAsync($body, $storefront)
    {
        return $this->bulkUpdateUnitsAsyncWithHttpInfo($body, $storefront)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation bulkUpdateUnitsAsyncWithHttpInfo
     *
     * Update some fields of a given set of units
     *
     * @param  \Kaufland\Seller\Model\UnitsBulkUpdateRequest[] $body Update Object (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bulkUpdateUnitsAsyncWithHttpInfo($body, $storefront)
    {
        $returnType = '\Kaufland\Seller\Model\UnitsBulkUpdateResponse';
        $request = $this->bulkUpdateUnitsRequest($body, $storefront);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'bulkUpdateUnits'
     *
     * @param  \Kaufland\Seller\Model\UnitsBulkUpdateRequest[] $body Update Object (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function bulkUpdateUnitsRequest($body, $storefront)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling bulkUpdateUnits'
            );
        }
        // verify the required parameter 'storefront' is set
        if ($storefront === null || (is_array($storefront) && count($storefront) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront when calling bulkUpdateUnits'
            );
        }

        $resourcePath = '/units/bulk';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($storefront !== null) {
            $queryParams['storefront'] = ObjectSerializer::toQueryValue($storefront, null);
        }


        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation createUnit
     *
     * Add a unit
     *
     * @param  \Kaufland\Seller\Model\UnitRequest $body Information about the unit that will be generated (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     *
     * @throws \Kaufland\Seller\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Kaufland\Seller\Model\ApiResponseUnit_
     */
    public function createUnit($body, $storefront)
    {
        list($response) = $this->createUnitWithHttpInfo($body, $storefront);
        return $response;
    }

    /**
     * Operation createUnitWithHttpInfo
     *
     * Add a unit
     *
     * @param  \Kaufland\Seller\Model\UnitRequest $body Information about the unit that will be generated (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     *
     * @throws \Kaufland\Seller\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Kaufland\Seller\Model\ApiResponseUnit_, HTTP status code, HTTP response headers (array of strings)
     */
    public function createUnitWithHttpInfo($body, $storefront)
    {
        $returnType = '\Kaufland\Seller\Model\ApiResponseUnit_';
        $request = $this->createUnitRequest($body, $storefront);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ApiResponseUnit_',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createUnitAsync
     *
     * Add a unit
     *
     * @param  \Kaufland\Seller\Model\UnitRequest $body Information about the unit that will be generated (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createUnitAsync($body, $storefront)
    {
        return $this->createUnitAsyncWithHttpInfo($body, $storefront)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createUnitAsyncWithHttpInfo
     *
     * Add a unit
     *
     * @param  \Kaufland\Seller\Model\UnitRequest $body Information about the unit that will be generated (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createUnitAsyncWithHttpInfo($body, $storefront)
    {
        $returnType = '\Kaufland\Seller\Model\ApiResponseUnit_';
        $request = $this->createUnitRequest($body, $storefront);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createUnit'
     *
     * @param  \Kaufland\Seller\Model\UnitRequest $body Information about the unit that will be generated (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function createUnitRequest($body, $storefront)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling createUnit'
            );
        }
        // verify the required parameter 'storefront' is set
        if ($storefront === null || (is_array($storefront) && count($storefront) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront when calling createUnit'
            );
        }

        $resourcePath = '/units';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($storefront !== null) {
            $queryParams['storefront'] = ObjectSerializer::toQueryValue($storefront, null);
        }


        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteUnit
     *
     * Delete a unit
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     *
     * @throws \Kaufland\Seller\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteUnit($id_unit, $storefront)
    {
        $this->deleteUnitWithHttpInfo($id_unit, $storefront);
    }

    /**
     * Operation deleteUnitWithHttpInfo
     *
     * Delete a unit
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     *
     * @throws \Kaufland\Seller\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteUnitWithHttpInfo($id_unit, $storefront)
    {
        $returnType = '';
        $request = $this->deleteUnitRequest($id_unit, $storefront);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteUnitAsync
     *
     * Delete a unit
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteUnitAsync($id_unit, $storefront)
    {
        return $this->deleteUnitAsyncWithHttpInfo($id_unit, $storefront)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteUnitAsyncWithHttpInfo
     *
     * Delete a unit
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteUnitAsyncWithHttpInfo($id_unit, $storefront)
    {
        $returnType = '';
        $request = $this->deleteUnitRequest($id_unit, $storefront);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteUnit'
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function deleteUnitRequest($id_unit, $storefront)
    {
        // verify the required parameter 'id_unit' is set
        if ($id_unit === null || (is_array($id_unit) && count($id_unit) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_unit when calling deleteUnit'
            );
        }
        // verify the required parameter 'storefront' is set
        if ($storefront === null || (is_array($storefront) && count($storefront) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront when calling deleteUnit'
            );
        }

        $resourcePath = '/units/{id_unit}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($storefront !== null) {
            $queryParams['storefront'] = ObjectSerializer::toQueryValue($storefront, null);
        }

        // path params
        if ($id_unit !== null) {
            $resourcePath = str_replace(
                '{' . 'id_unit' . '}',
                ObjectSerializer::toPathValue($id_unit),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getUnit
     *
     * Get a unit by ID
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \Kaufland\Seller\Model\UnitEmbeddedEnum[] $embedded embedded (optional)
     *
     * @throws \Kaufland\Seller\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Kaufland\Seller\Model\ApiResponseUnit_
     */
    public function getUnit($id_unit, $storefront, $embedded = null)
    {
        list($response) = $this->getUnitWithHttpInfo($id_unit, $storefront, $embedded);
        return $response;
    }

    /**
     * Operation getUnitWithHttpInfo
     *
     * Get a unit by ID
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \Kaufland\Seller\Model\UnitEmbeddedEnum[] $embedded (optional)
     *
     * @throws \Kaufland\Seller\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Kaufland\Seller\Model\ApiResponseUnit_, HTTP status code, HTTP response headers (array of strings)
     */
    public function getUnitWithHttpInfo($id_unit, $storefront, $embedded = null)
    {
        $returnType = '\Kaufland\Seller\Model\ApiResponseUnit_';
        $request = $this->getUnitRequest($id_unit, $storefront, $embedded);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ApiResponseUnit_',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getUnitAsync
     *
     * Get a unit by ID
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \Kaufland\Seller\Model\UnitEmbeddedEnum[] $embedded (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUnitAsync($id_unit, $storefront, $embedded = null)
    {
        return $this->getUnitAsyncWithHttpInfo($id_unit, $storefront, $embedded)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getUnitAsyncWithHttpInfo
     *
     * Get a unit by ID
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \Kaufland\Seller\Model\UnitEmbeddedEnum[] $embedded (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUnitAsyncWithHttpInfo($id_unit, $storefront, $embedded = null)
    {
        $returnType = '\Kaufland\Seller\Model\ApiResponseUnit_';
        $request = $this->getUnitRequest($id_unit, $storefront, $embedded);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getUnit'
     *
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     * @param  \Kaufland\Seller\Model\UnitEmbeddedEnum[] $embedded (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getUnitRequest($id_unit, $storefront, $embedded = null)
    {
        // verify the required parameter 'id_unit' is set
        if ($id_unit === null || (is_array($id_unit) && count($id_unit) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_unit when calling getUnit'
            );
        }
        // verify the required parameter 'storefront' is set
        if ($storefront === null || (is_array($storefront) && count($storefront) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront when calling getUnit'
            );
        }

        $resourcePath = '/units/{id_unit}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($storefront !== null) {
            $queryParams['storefront'] = ObjectSerializer::toQueryValue($storefront, null);
        }
        // query params
        if (is_array($embedded)) {
            $embedded = ObjectSerializer::serializeCollection($embedded, 'multi', true);
        }
        if ($embedded !== null) {
            $queryParams['embedded'] = ObjectSerializer::toQueryValue($embedded, null);
        }

        // path params
        if ($id_unit !== null) {
            $resourcePath = str_replace(
                '{' . 'id_unit' . '}',
                ObjectSerializer::toPathValue($id_unit),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getUnits
     *
     * Get a list of your units
     *
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     * @param  int $limit Desired size of result set, maximum is 100 (optional, default to 30)
     * @param  int $offset Offset applied to result set (optional, default to 0)
     * @param  string $id_offer Provided ID of your stock (optional)
     * @param  int $id_product Our internal id_product (optional)
     * @param  string $ean EAN, 13 or 14 digits (optional)
     * @param  \Kaufland\Seller\Model\UnitEmbeddedEnum[] $embedded embedded (optional)
     * @param  \Kaufland\Seller\Model\FulfillmentType[] $fulfillment_type Get only units which are fulfilled by the given type (optional, default to ["fulfilled_by_merchant"])
     *
     * @throws \Kaufland\Seller\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Kaufland\Seller\Model\CollectionApiResponseUnitEmbedded_
     */
    public function getUnits($storefront, $limit = '30', $offset = '0', $id_offer = null, $id_product = null, $ean = null, $embedded = null, $fulfillment_type = '["fulfilled_by_merchant"]')
    {
        list($response) = $this->getUnitsWithHttpInfo($storefront, $limit, $offset, $id_offer, $id_product, $ean, $embedded, $fulfillment_type);
        return $response;
    }

    /**
     * Operation getUnitsWithHttpInfo
     *
     * Get a list of your units
     *
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     * @param  int $limit Desired size of result set, maximum is 100 (optional, default to 30)
     * @param  int $offset Offset applied to result set (optional, default to 0)
     * @param  string $id_offer Provided ID of your stock (optional)
     * @param  int $id_product Our internal id_product (optional)
     * @param  string $ean EAN, 13 or 14 digits (optional)
     * @param  \Kaufland\Seller\Model\UnitEmbeddedEnum[] $embedded (optional)
     * @param  \Kaufland\Seller\Model\FulfillmentType[] $fulfillment_type Get only units which are fulfilled by the given type (optional, default to ["fulfilled_by_merchant"])
     *
     * @throws \Kaufland\Seller\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Kaufland\Seller\Model\CollectionApiResponseUnitEmbedded_, HTTP status code, HTTP response headers (array of strings)
     */
    public function getUnitsWithHttpInfo($storefront, $limit = '30', $offset = '0', $id_offer = null, $id_product = null, $ean = null, $embedded = null, $fulfillment_type = '["fulfilled_by_merchant"]')
    {
        $returnType = '\Kaufland\Seller\Model\CollectionApiResponseUnitEmbedded_';
        $request = $this->getUnitsRequest($storefront, $limit, $offset, $id_offer, $id_product, $ean, $embedded, $fulfillment_type);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\CollectionApiResponseUnitEmbedded_',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getUnitsAsync
     *
     * Get a list of your units
     *
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     * @param  int $limit Desired size of result set, maximum is 100 (optional, default to 30)
     * @param  int $offset Offset applied to result set (optional, default to 0)
     * @param  string $id_offer Provided ID of your stock (optional)
     * @param  int $id_product Our internal id_product (optional)
     * @param  string $ean EAN, 13 or 14 digits (optional)
     * @param  \Kaufland\Seller\Model\UnitEmbeddedEnum[] $embedded (optional)
     * @param  \Kaufland\Seller\Model\FulfillmentType[] $fulfillment_type Get only units which are fulfilled by the given type (optional, default to ["fulfilled_by_merchant"])
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUnitsAsync($storefront, $limit = '30', $offset = '0', $id_offer = null, $id_product = null, $ean = null, $embedded = null, $fulfillment_type = '["fulfilled_by_merchant"]')
    {
        return $this->getUnitsAsyncWithHttpInfo($storefront, $limit, $offset, $id_offer, $id_product, $ean, $embedded, $fulfillment_type)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getUnitsAsyncWithHttpInfo
     *
     * Get a list of your units
     *
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     * @param  int $limit Desired size of result set, maximum is 100 (optional, default to 30)
     * @param  int $offset Offset applied to result set (optional, default to 0)
     * @param  string $id_offer Provided ID of your stock (optional)
     * @param  int $id_product Our internal id_product (optional)
     * @param  string $ean EAN, 13 or 14 digits (optional)
     * @param  \Kaufland\Seller\Model\UnitEmbeddedEnum[] $embedded (optional)
     * @param  \Kaufland\Seller\Model\FulfillmentType[] $fulfillment_type Get only units which are fulfilled by the given type (optional, default to ["fulfilled_by_merchant"])
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUnitsAsyncWithHttpInfo($storefront, $limit = '30', $offset = '0', $id_offer = null, $id_product = null, $ean = null, $embedded = null, $fulfillment_type = '["fulfilled_by_merchant"]')
    {
        $returnType = '\Kaufland\Seller\Model\CollectionApiResponseUnitEmbedded_';
        $request = $this->getUnitsRequest($storefront, $limit, $offset, $id_offer, $id_product, $ean, $embedded, $fulfillment_type);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getUnits'
     *
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     * @param  int $limit Desired size of result set, maximum is 100 (optional, default to 30)
     * @param  int $offset Offset applied to result set (optional, default to 0)
     * @param  string $id_offer Provided ID of your stock (optional)
     * @param  int $id_product Our internal id_product (optional)
     * @param  string $ean EAN, 13 or 14 digits (optional)
     * @param  \Kaufland\Seller\Model\UnitEmbeddedEnum[] $embedded (optional)
     * @param  \Kaufland\Seller\Model\FulfillmentType[] $fulfillment_type Get only units which are fulfilled by the given type (optional, default to ["fulfilled_by_merchant"])
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getUnitsRequest($storefront, $limit = '30', $offset = '0', $id_offer = null, $id_product = null, $ean = null, $embedded = null, $fulfillment_type = '["fulfilled_by_merchant"]')
    {
        // verify the required parameter 'storefront' is set
        if ($storefront === null || (is_array($storefront) && count($storefront) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront when calling getUnits'
            );
        }

        $resourcePath = '/units';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit, 'int32');
        }
        // query params
        if ($offset !== null) {
            $queryParams['offset'] = ObjectSerializer::toQueryValue($offset, 'int32');
        }
        // query params
        if ($storefront !== null) {
            $queryParams['storefront'] = ObjectSerializer::toQueryValue($storefront, null);
        }
        // query params
        if ($id_offer !== null) {
            $queryParams['id_offer'] = ObjectSerializer::toQueryValue($id_offer, null);
        }
        // query params
        if ($id_product !== null) {
            $queryParams['id_product'] = ObjectSerializer::toQueryValue($id_product, 'int64');
        }
        // query params
        if ($ean !== null) {
            $queryParams['ean'] = ObjectSerializer::toQueryValue($ean, null);
        }
        // query params
        if (is_array($embedded)) {
            $embedded = ObjectSerializer::serializeCollection($embedded, 'multi', true);
        }
        if ($embedded !== null) {
            $queryParams['embedded'] = ObjectSerializer::toQueryValue($embedded, null);
        }
        // query params
        if (is_array($fulfillment_type)) {
            $fulfillment_type = ObjectSerializer::serializeCollection($fulfillment_type, 'multi', true);
        }
        if ($fulfillment_type !== null) {
            $queryParams['fulfillment_type'] = ObjectSerializer::toQueryValue($fulfillment_type, null);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation patchUnit
     *
     * Update some of the fields of a unit
     *
     * @param  \Kaufland\Seller\Model\UnitPatchRequest $body Update Object (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     *
     * @throws \Kaufland\Seller\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Kaufland\Seller\Model\ApiResponseUnit_
     */
    public function patchUnit($body, $storefront, $id_unit)
    {
        list($response) = $this->patchUnitWithHttpInfo($body, $storefront, $id_unit);
        return $response;
    }

    /**
     * Operation patchUnitWithHttpInfo
     *
     * Update some of the fields of a unit
     *
     * @param  \Kaufland\Seller\Model\UnitPatchRequest $body Update Object (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     *
     * @throws \Kaufland\Seller\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Kaufland\Seller\Model\ApiResponseUnit_, HTTP status code, HTTP response headers (array of strings)
     */
    public function patchUnitWithHttpInfo($body, $storefront, $id_unit)
    {
        $returnType = '\Kaufland\Seller\Model\ApiResponseUnit_';
        $request = $this->patchUnitRequest($body, $storefront, $id_unit);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ApiResponseUnit_',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Kaufland\Seller\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation patchUnitAsync
     *
     * Update some of the fields of a unit
     *
     * @param  \Kaufland\Seller\Model\UnitPatchRequest $body Update Object (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchUnitAsync($body, $storefront, $id_unit)
    {
        return $this->patchUnitAsyncWithHttpInfo($body, $storefront, $id_unit)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation patchUnitAsyncWithHttpInfo
     *
     * Update some of the fields of a unit
     *
     * @param  \Kaufland\Seller\Model\UnitPatchRequest $body Update Object (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchUnitAsyncWithHttpInfo($body, $storefront, $id_unit)
    {
        $returnType = '\Kaufland\Seller\Model\ApiResponseUnit_';
        $request = $this->patchUnitRequest($body, $storefront, $id_unit);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'patchUnit'
     *
     * @param  \Kaufland\Seller\Model\UnitPatchRequest $body Update Object (required)
     * @param  \Kaufland\Seller\Model\Storefront $storefront Parameter to select the affected storefront (required)
     * @param  int $id_unit Internal ID of Unit, unique across all Units (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function patchUnitRequest($body, $storefront, $id_unit)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling patchUnit'
            );
        }
        // verify the required parameter 'storefront' is set
        if ($storefront === null || (is_array($storefront) && count($storefront) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storefront when calling patchUnit'
            );
        }
        // verify the required parameter 'id_unit' is set
        if ($id_unit === null || (is_array($id_unit) && count($id_unit) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id_unit when calling patchUnit'
            );
        }

        $resourcePath = '/units/{id_unit}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($storefront !== null) {
            $queryParams['storefront'] = ObjectSerializer::toQueryValue($storefront, null);
        }

        // path params
        if ($id_unit !== null) {
            $resourcePath = str_replace(
                '{' . 'id_unit' . '}',
                ObjectSerializer::toPathValue($id_unit),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'PATCH',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
