<?php
/**
 * CategoryTree
 *
 * PHP version 5
 *
 * @category Class
 * @package  Cbdesk\Kauflandv2\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * OpenAPI spec version: 2.9.1
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.42
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Cbdesk\Kauflandv2\Api\Model;

use \ArrayAccess;
use \Cbdesk\Kauflandv2\Api\ObjectSerializer;

/**
 * CategoryTree Class Doc Comment
 *
 * @category Class
 * @package  Cbdesk\Kauflandv2\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CategoryTree implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CategoryTree';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id_category' => 'int',
'name' => 'string',
'id_parent_category' => 'int',
'title_singular' => 'string',
'title_plural' => 'string',
'level' => 'double',
'url' => 'string',
'shipping_category' => 'string',
'variable_fee' => 'double',
'fixed_fee' => 'double',
'vat' => 'double',
'children' => '\Cbdesk\Kauflandv2\Api\Model\CategoryTree[]'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id_category' => 'int64',
'name' => null,
'id_parent_category' => 'int64',
'title_singular' => null,
'title_plural' => null,
'level' => 'double',
'url' => null,
'shipping_category' => null,
'variable_fee' => 'double',
'fixed_fee' => 'double',
'vat' => 'double',
'children' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id_category' => 'id_category',
'name' => 'name',
'id_parent_category' => 'id_parent_category',
'title_singular' => 'title_singular',
'title_plural' => 'title_plural',
'level' => 'level',
'url' => 'url',
'shipping_category' => 'shipping_category',
'variable_fee' => 'variable_fee',
'fixed_fee' => 'fixed_fee',
'vat' => 'vat',
'children' => 'children'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id_category' => 'setIdCategory',
'name' => 'setName',
'id_parent_category' => 'setIdParentCategory',
'title_singular' => 'setTitleSingular',
'title_plural' => 'setTitlePlural',
'level' => 'setLevel',
'url' => 'setUrl',
'shipping_category' => 'setShippingCategory',
'variable_fee' => 'setVariableFee',
'fixed_fee' => 'setFixedFee',
'vat' => 'setVat',
'children' => 'setChildren'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id_category' => 'getIdCategory',
'name' => 'getName',
'id_parent_category' => 'getIdParentCategory',
'title_singular' => 'getTitleSingular',
'title_plural' => 'getTitlePlural',
'level' => 'getLevel',
'url' => 'getUrl',
'shipping_category' => 'getShippingCategory',
'variable_fee' => 'getVariableFee',
'fixed_fee' => 'getFixedFee',
'vat' => 'getVat',
'children' => 'getChildren'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id_category'] = isset($data['id_category']) ? $data['id_category'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['id_parent_category'] = isset($data['id_parent_category']) ? $data['id_parent_category'] : null;
        $this->container['title_singular'] = isset($data['title_singular']) ? $data['title_singular'] : null;
        $this->container['title_plural'] = isset($data['title_plural']) ? $data['title_plural'] : null;
        $this->container['level'] = isset($data['level']) ? $data['level'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['shipping_category'] = isset($data['shipping_category']) ? $data['shipping_category'] : null;
        $this->container['variable_fee'] = isset($data['variable_fee']) ? $data['variable_fee'] : null;
        $this->container['fixed_fee'] = isset($data['fixed_fee']) ? $data['fixed_fee'] : null;
        $this->container['vat'] = isset($data['vat']) ? $data['vat'] : null;
        $this->container['children'] = isset($data['children']) ? $data['children'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id_category'] === null) {
            $invalidProperties[] = "'id_category' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['id_parent_category'] === null) {
            $invalidProperties[] = "'id_parent_category' can't be null";
        }
        if ($this->container['title_singular'] === null) {
            $invalidProperties[] = "'title_singular' can't be null";
        }
        if ($this->container['title_plural'] === null) {
            $invalidProperties[] = "'title_plural' can't be null";
        }
        if ($this->container['level'] === null) {
            $invalidProperties[] = "'level' can't be null";
        }
        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        if ($this->container['shipping_category'] === null) {
            $invalidProperties[] = "'shipping_category' can't be null";
        }
        if ($this->container['variable_fee'] === null) {
            $invalidProperties[] = "'variable_fee' can't be null";
        }
        if ($this->container['fixed_fee'] === null) {
            $invalidProperties[] = "'fixed_fee' can't be null";
        }
        if ($this->container['vat'] === null) {
            $invalidProperties[] = "'vat' can't be null";
        }
        if ($this->container['children'] === null) {
            $invalidProperties[] = "'children' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id_category
     *
     * @return int
     */
    public function getIdCategory()
    {
        return $this->container['id_category'];
    }

    /**
     * Sets id_category
     *
     * @param int $id_category id_category
     *
     * @return $this
     */
    public function setIdCategory($id_category)
    {
        $this->container['id_category'] = $id_category;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets id_parent_category
     *
     * @return int
     */
    public function getIdParentCategory()
    {
        return $this->container['id_parent_category'];
    }

    /**
     * Sets id_parent_category
     *
     * @param int $id_parent_category id_parent_category
     *
     * @return $this
     */
    public function setIdParentCategory($id_parent_category)
    {
        $this->container['id_parent_category'] = $id_parent_category;

        return $this;
    }

    /**
     * Gets title_singular
     *
     * @return string
     */
    public function getTitleSingular()
    {
        return $this->container['title_singular'];
    }

    /**
     * Sets title_singular
     *
     * @param string $title_singular title_singular
     *
     * @return $this
     */
    public function setTitleSingular($title_singular)
    {
        $this->container['title_singular'] = $title_singular;

        return $this;
    }

    /**
     * Gets title_plural
     *
     * @return string
     */
    public function getTitlePlural()
    {
        return $this->container['title_plural'];
    }

    /**
     * Sets title_plural
     *
     * @param string $title_plural title_plural
     *
     * @return $this
     */
    public function setTitlePlural($title_plural)
    {
        $this->container['title_plural'] = $title_plural;

        return $this;
    }

    /**
     * Gets level
     *
     * @return double
     */
    public function getLevel()
    {
        return $this->container['level'];
    }

    /**
     * Sets level
     *
     * @param double $level level
     *
     * @return $this
     */
    public function setLevel($level)
    {
        $this->container['level'] = $level;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url url
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets shipping_category
     *
     * @return string
     */
    public function getShippingCategory()
    {
        return $this->container['shipping_category'];
    }

    /**
     * Sets shipping_category
     *
     * @param string $shipping_category shipping_category
     *
     * @return $this
     */
    public function setShippingCategory($shipping_category)
    {
        $this->container['shipping_category'] = $shipping_category;

        return $this;
    }

    /**
     * Gets variable_fee
     *
     * @return double
     */
    public function getVariableFee()
    {
        return $this->container['variable_fee'];
    }

    /**
     * Sets variable_fee
     *
     * @param double $variable_fee variable_fee
     *
     * @return $this
     */
    public function setVariableFee($variable_fee)
    {
        $this->container['variable_fee'] = $variable_fee;

        return $this;
    }

    /**
     * Gets fixed_fee
     *
     * @return double
     */
    public function getFixedFee()
    {
        return $this->container['fixed_fee'];
    }

    /**
     * Sets fixed_fee
     *
     * @param double $fixed_fee fixed_fee
     *
     * @return $this
     */
    public function setFixedFee($fixed_fee)
    {
        $this->container['fixed_fee'] = $fixed_fee;

        return $this;
    }

    /**
     * Gets vat
     *
     * @return double
     */
    public function getVat()
    {
        return $this->container['vat'];
    }

    /**
     * Sets vat
     *
     * @param double $vat vat
     *
     * @return $this
     */
    public function setVat($vat)
    {
        $this->container['vat'] = $vat;

        return $this;
    }

    /**
     * Gets children
     *
     * @return \Cbdesk\Kauflandv2\Api\Model\CategoryTree[]
     */
    public function getChildren()
    {
        return $this->container['children'];
    }

    /**
     * Sets children
     *
     * @param \Cbdesk\Kauflandv2\Api\Model\CategoryTree[] $children children
     *
     * @return $this
     */
    public function setChildren($children)
    {
        $this->container['children'] = $children;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
