<?php
/**
 * ImportFileOrderCommand
 *
 * PHP version 5
 *
 * @category Class
 * @package  Cbdesk\Kauflandv2\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * OpenAPI spec version: 2.9.1
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.42
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Cbdesk\Kauflandv2\Api\Model;

use \ArrayAccess;
use \Cbdesk\Kauflandv2\Api\ObjectSerializer;

/**
 * ImportFileOrderCommand Class Doc Comment
 *
 * @category Class
 * @package  Cbdesk\Kauflandv2\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ImportFileOrderCommand implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ImportFileOrderCommand';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'current_line' => 'int',
'error_count' => 'int',
'id_import_file' => 'int',
'note' => 'string',
'status' => '\Cbdesk\Kauflandv2\Api\Model\ImportStatus',
'total_lines' => 'int',
'ts_completed_iso' => '\DateTime',
'ts_created_iso' => '\DateTime',
'ts_last_row_updated_iso' => '\DateTime',
'ts_updated_iso' => '\DateTime',
'type' => '\Cbdesk\Kauflandv2\Api\Model\ImportType',
'uri' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'current_line' => 'int32',
'error_count' => 'int32',
'id_import_file' => 'int64',
'note' => null,
'status' => null,
'total_lines' => 'int32',
'ts_completed_iso' => 'date-time',
'ts_created_iso' => 'date-time',
'ts_last_row_updated_iso' => 'date-time',
'ts_updated_iso' => 'date-time',
'type' => null,
'uri' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'current_line' => 'current_line',
'error_count' => 'error_count',
'id_import_file' => 'id_import_file',
'note' => 'note',
'status' => 'status',
'total_lines' => 'total_lines',
'ts_completed_iso' => 'ts_completed_iso',
'ts_created_iso' => 'ts_created_iso',
'ts_last_row_updated_iso' => 'ts_last_row_updated_iso',
'ts_updated_iso' => 'ts_updated_iso',
'type' => 'type',
'uri' => 'uri'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'current_line' => 'setCurrentLine',
'error_count' => 'setErrorCount',
'id_import_file' => 'setIdImportFile',
'note' => 'setNote',
'status' => 'setStatus',
'total_lines' => 'setTotalLines',
'ts_completed_iso' => 'setTsCompletedIso',
'ts_created_iso' => 'setTsCreatedIso',
'ts_last_row_updated_iso' => 'setTsLastRowUpdatedIso',
'ts_updated_iso' => 'setTsUpdatedIso',
'type' => 'setType',
'uri' => 'setUri'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'current_line' => 'getCurrentLine',
'error_count' => 'getErrorCount',
'id_import_file' => 'getIdImportFile',
'note' => 'getNote',
'status' => 'getStatus',
'total_lines' => 'getTotalLines',
'ts_completed_iso' => 'getTsCompletedIso',
'ts_created_iso' => 'getTsCreatedIso',
'ts_last_row_updated_iso' => 'getTsLastRowUpdatedIso',
'ts_updated_iso' => 'getTsUpdatedIso',
'type' => 'getType',
'uri' => 'getUri'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['current_line'] = isset($data['current_line']) ? $data['current_line'] : null;
        $this->container['error_count'] = isset($data['error_count']) ? $data['error_count'] : null;
        $this->container['id_import_file'] = isset($data['id_import_file']) ? $data['id_import_file'] : null;
        $this->container['note'] = isset($data['note']) ? $data['note'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['total_lines'] = isset($data['total_lines']) ? $data['total_lines'] : null;
        $this->container['ts_completed_iso'] = isset($data['ts_completed_iso']) ? $data['ts_completed_iso'] : null;
        $this->container['ts_created_iso'] = isset($data['ts_created_iso']) ? $data['ts_created_iso'] : null;
        $this->container['ts_last_row_updated_iso'] = isset($data['ts_last_row_updated_iso']) ? $data['ts_last_row_updated_iso'] : null;
        $this->container['ts_updated_iso'] = isset($data['ts_updated_iso']) ? $data['ts_updated_iso'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['uri'] = isset($data['uri']) ? $data['uri'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['current_line'] === null) {
            $invalidProperties[] = "'current_line' can't be null";
        }
        if ($this->container['error_count'] === null) {
            $invalidProperties[] = "'error_count' can't be null";
        }
        if ($this->container['id_import_file'] === null) {
            $invalidProperties[] = "'id_import_file' can't be null";
        }
        if ($this->container['note'] === null) {
            $invalidProperties[] = "'note' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['total_lines'] === null) {
            $invalidProperties[] = "'total_lines' can't be null";
        }
        if ($this->container['ts_completed_iso'] === null) {
            $invalidProperties[] = "'ts_completed_iso' can't be null";
        }
        if ($this->container['ts_created_iso'] === null) {
            $invalidProperties[] = "'ts_created_iso' can't be null";
        }
        if ($this->container['ts_last_row_updated_iso'] === null) {
            $invalidProperties[] = "'ts_last_row_updated_iso' can't be null";
        }
        if ($this->container['ts_updated_iso'] === null) {
            $invalidProperties[] = "'ts_updated_iso' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['uri'] === null) {
            $invalidProperties[] = "'uri' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets current_line
     *
     * @return int
     */
    public function getCurrentLine()
    {
        return $this->container['current_line'];
    }

    /**
     * Sets current_line
     *
     * @param int $current_line current_line
     *
     * @return $this
     */
    public function setCurrentLine($current_line)
    {
        $this->container['current_line'] = $current_line;

        return $this;
    }

    /**
     * Gets error_count
     *
     * @return int
     */
    public function getErrorCount()
    {
        return $this->container['error_count'];
    }

    /**
     * Sets error_count
     *
     * @param int $error_count error_count
     *
     * @return $this
     */
    public function setErrorCount($error_count)
    {
        $this->container['error_count'] = $error_count;

        return $this;
    }

    /**
     * Gets id_import_file
     *
     * @return int
     */
    public function getIdImportFile()
    {
        return $this->container['id_import_file'];
    }

    /**
     * Sets id_import_file
     *
     * @param int $id_import_file Internal ID of Import File, unique across all Import Files
     *
     * @return $this
     */
    public function setIdImportFile($id_import_file)
    {
        $this->container['id_import_file'] = $id_import_file;

        return $this;
    }

    /**
     * Gets note
     *
     * @return string
     */
    public function getNote()
    {
        return $this->container['note'];
    }

    /**
     * Sets note
     *
     * @param string $note note
     *
     * @return $this
     */
    public function setNote($note)
    {
        $this->container['note'] = $note;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Cbdesk\Kauflandv2\Api\Model\ImportStatus
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Cbdesk\Kauflandv2\Api\Model\ImportStatus $status status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets total_lines
     *
     * @return int
     */
    public function getTotalLines()
    {
        return $this->container['total_lines'];
    }

    /**
     * Sets total_lines
     *
     * @param int $total_lines total_lines
     *
     * @return $this
     */
    public function setTotalLines($total_lines)
    {
        $this->container['total_lines'] = $total_lines;

        return $this;
    }

    /**
     * Gets ts_completed_iso
     *
     * @return \DateTime
     */
    public function getTsCompletedIso()
    {
        return $this->container['ts_completed_iso'];
    }

    /**
     * Sets ts_completed_iso
     *
     * @param \DateTime $ts_completed_iso ts_completed_iso
     *
     * @return $this
     */
    public function setTsCompletedIso($ts_completed_iso)
    {
        $this->container['ts_completed_iso'] = $ts_completed_iso;

        return $this;
    }

    /**
     * Gets ts_created_iso
     *
     * @return \DateTime
     */
    public function getTsCreatedIso()
    {
        return $this->container['ts_created_iso'];
    }

    /**
     * Sets ts_created_iso
     *
     * @param \DateTime $ts_created_iso ts_created_iso
     *
     * @return $this
     */
    public function setTsCreatedIso($ts_created_iso)
    {
        $this->container['ts_created_iso'] = $ts_created_iso;

        return $this;
    }

    /**
     * Gets ts_last_row_updated_iso
     *
     * @return \DateTime
     */
    public function getTsLastRowUpdatedIso()
    {
        return $this->container['ts_last_row_updated_iso'];
    }

    /**
     * Sets ts_last_row_updated_iso
     *
     * @param \DateTime $ts_last_row_updated_iso ts_last_row_updated_iso
     *
     * @return $this
     */
    public function setTsLastRowUpdatedIso($ts_last_row_updated_iso)
    {
        $this->container['ts_last_row_updated_iso'] = $ts_last_row_updated_iso;

        return $this;
    }

    /**
     * Gets ts_updated_iso
     *
     * @return \DateTime
     */
    public function getTsUpdatedIso()
    {
        return $this->container['ts_updated_iso'];
    }

    /**
     * Sets ts_updated_iso
     *
     * @param \DateTime $ts_updated_iso ts_updated_iso
     *
     * @return $this
     */
    public function setTsUpdatedIso($ts_updated_iso)
    {
        $this->container['ts_updated_iso'] = $ts_updated_iso;

        return $this;
    }

    /**
     * Gets type
     *
     * @return \Cbdesk\Kauflandv2\Api\Model\ImportType
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \Cbdesk\Kauflandv2\Api\Model\ImportType $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets uri
     *
     * @return string
     */
    public function getUri()
    {
        return $this->container['uri'];
    }

    /**
     * Sets uri
     *
     * @param string $uri uri
     *
     * @return $this
     */
    public function setUri($uri)
    {
        $this->container['uri'] = $uri;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
