<?php
/**
 * OrderUnitEmbeddable
 *
 * PHP version 5
 *
 * @category Class
 * @package  Kaufland\Seller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * OpenAPI spec version: 2.13.1
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Kaufland\Seller\Model;
use \Kaufland\Seller\ObjectSerializer;

/**
 * OrderUnitEmbeddable Class Doc Comment
 *
 * @category Class
 * @description Additional data to be returned for order unit
 * @package  Kaufland\Seller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderUnitEmbeddable
{
    /**
     * Possible values of this enum
     */
    const DELIVERY_ATTEMPT_TIMESTAMP_ISO = 'delivery_attempt_timestamp_iso';
    const RETURN_UNIT = 'return_unit';
    const TICKETS = 'tickets';
    const DELIVERY = 'delivery';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DELIVERY_ATTEMPT_TIMESTAMP_ISO
            self::RETURN_UNIT
            self::TICKETS
            self::DELIVERY
        ];
    }
}
