<?php
/**
 * OrderDetails
 *
 * PHP version 5
 *
 * @category Class
 * @package  Cbdesk\Kauflandv2\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * OpenAPI spec version: 2.9.1
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.42
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Cbdesk\Kauflandv2\Api\Model;

use \ArrayAccess;
use \Cbdesk\Kauflandv2\Api\ObjectSerializer;

/**
 * OrderDetails Class Doc Comment
 *
 * @category Class
 * @package  Cbdesk\Kauflandv2\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderDetails implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'OrderDetails';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id_order' => 'string',
'ts_created_iso' => '\DateTime',
'is_marketplace_deemed_supplier' => 'bool',
'storefront' => '\Cbdesk\Kauflandv2\Api\Model\Storefront',
'fulfillment_type' => '\Cbdesk\Kauflandv2\Api\Model\FulfillmentType',
'order_units' => '\Cbdesk\Kauflandv2\Api\Model\OrderDetailsOrderUnits[]',
'billing_address' => 'AllOfOrderDetailsBillingAddress',
'shipping_address' => 'AllOfOrderDetailsShippingAddress',
'buyer' => 'AllOfOrderDetailsBuyer',
'order_invoices' => '\Cbdesk\Kauflandv2\Api\Model\OrderInvoice[]'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id_order' => null,
'ts_created_iso' => 'date-time',
'is_marketplace_deemed_supplier' => null,
'storefront' => null,
'fulfillment_type' => null,
'order_units' => null,
'billing_address' => null,
'shipping_address' => null,
'buyer' => null,
'order_invoices' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id_order' => 'id_order',
'ts_created_iso' => 'ts_created_iso',
'is_marketplace_deemed_supplier' => 'is_marketplace_deemed_supplier',
'storefront' => 'storefront',
'fulfillment_type' => 'fulfillment_type',
'order_units' => 'order_units',
'billing_address' => 'billing_address',
'shipping_address' => 'shipping_address',
'buyer' => 'buyer',
'order_invoices' => 'order_invoices'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id_order' => 'setIdOrder',
'ts_created_iso' => 'setTsCreatedIso',
'is_marketplace_deemed_supplier' => 'setIsMarketplaceDeemedSupplier',
'storefront' => 'setStorefront',
'fulfillment_type' => 'setFulfillmentType',
'order_units' => 'setOrderUnits',
'billing_address' => 'setBillingAddress',
'shipping_address' => 'setShippingAddress',
'buyer' => 'setBuyer',
'order_invoices' => 'setOrderInvoices'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id_order' => 'getIdOrder',
'ts_created_iso' => 'getTsCreatedIso',
'is_marketplace_deemed_supplier' => 'getIsMarketplaceDeemedSupplier',
'storefront' => 'getStorefront',
'fulfillment_type' => 'getFulfillmentType',
'order_units' => 'getOrderUnits',
'billing_address' => 'getBillingAddress',
'shipping_address' => 'getShippingAddress',
'buyer' => 'getBuyer',
'order_invoices' => 'getOrderInvoices'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id_order'] = isset($data['id_order']) ? $data['id_order'] : null;
        $this->container['ts_created_iso'] = isset($data['ts_created_iso']) ? $data['ts_created_iso'] : null;
        $this->container['is_marketplace_deemed_supplier'] = isset($data['is_marketplace_deemed_supplier']) ? $data['is_marketplace_deemed_supplier'] : null;
        $this->container['storefront'] = isset($data['storefront']) ? $data['storefront'] : null;
        $this->container['fulfillment_type'] = isset($data['fulfillment_type']) ? $data['fulfillment_type'] : null;
        $this->container['order_units'] = isset($data['order_units']) ? $data['order_units'] : null;
        $this->container['billing_address'] = isset($data['billing_address']) ? $data['billing_address'] : null;
        $this->container['shipping_address'] = isset($data['shipping_address']) ? $data['shipping_address'] : null;
        $this->container['buyer'] = isset($data['buyer']) ? $data['buyer'] : null;
        $this->container['order_invoices'] = isset($data['order_invoices']) ? $data['order_invoices'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id_order'] === null) {
            $invalidProperties[] = "'id_order' can't be null";
        }
        if ($this->container['ts_created_iso'] === null) {
            $invalidProperties[] = "'ts_created_iso' can't be null";
        }
        if ($this->container['is_marketplace_deemed_supplier'] === null) {
            $invalidProperties[] = "'is_marketplace_deemed_supplier' can't be null";
        }
        if ($this->container['storefront'] === null) {
            $invalidProperties[] = "'storefront' can't be null";
        }
        if ($this->container['fulfillment_type'] === null) {
            $invalidProperties[] = "'fulfillment_type' can't be null";
        }
        if ($this->container['order_units'] === null) {
            $invalidProperties[] = "'order_units' can't be null";
        }
        if ($this->container['billing_address'] === null) {
            $invalidProperties[] = "'billing_address' can't be null";
        }
        if ($this->container['shipping_address'] === null) {
            $invalidProperties[] = "'shipping_address' can't be null";
        }
        if ($this->container['buyer'] === null) {
            $invalidProperties[] = "'buyer' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id_order
     *
     * @return string
     */
    public function getIdOrder()
    {
        return $this->container['id_order'];
    }

    /**
     * Sets id_order
     *
     * @param string $id_order id_order
     *
     * @return $this
     */
    public function setIdOrder($id_order)
    {
        $this->container['id_order'] = $id_order;

        return $this;
    }

    /**
     * Gets ts_created_iso
     *
     * @return \DateTime
     */
    public function getTsCreatedIso()
    {
        return $this->container['ts_created_iso'];
    }

    /**
     * Sets ts_created_iso
     *
     * @param \DateTime $ts_created_iso ts_created_iso
     *
     * @return $this
     */
    public function setTsCreatedIso($ts_created_iso)
    {
        $this->container['ts_created_iso'] = $ts_created_iso;

        return $this;
    }

    /**
     * Gets is_marketplace_deemed_supplier
     *
     * @return bool
     */
    public function getIsMarketplaceDeemedSupplier()
    {
        return $this->container['is_marketplace_deemed_supplier'];
    }

    /**
     * Sets is_marketplace_deemed_supplier
     *
     * @param bool $is_marketplace_deemed_supplier is_marketplace_deemed_supplier
     *
     * @return $this
     */
    public function setIsMarketplaceDeemedSupplier($is_marketplace_deemed_supplier)
    {
        $this->container['is_marketplace_deemed_supplier'] = $is_marketplace_deemed_supplier;

        return $this;
    }

    /**
     * Gets storefront
     *
     * @return \Cbdesk\Kauflandv2\Api\Model\Storefront
     */
    public function getStorefront()
    {
        return $this->container['storefront'];
    }

    /**
     * Sets storefront
     *
     * @param \Cbdesk\Kauflandv2\Api\Model\Storefront $storefront storefront
     *
     * @return $this
     */
    public function setStorefront($storefront)
    {
        $this->container['storefront'] = $storefront;

        return $this;
    }

    /**
     * Gets fulfillment_type
     *
     * @return \Cbdesk\Kauflandv2\Api\Model\FulfillmentType
     */
    public function getFulfillmentType()
    {
        return $this->container['fulfillment_type'];
    }

    /**
     * Sets fulfillment_type
     *
     * @param \Cbdesk\Kauflandv2\Api\Model\FulfillmentType $fulfillment_type fulfillment_type
     *
     * @return $this
     */
    public function setFulfillmentType($fulfillment_type)
    {
        $this->container['fulfillment_type'] = $fulfillment_type;

        return $this;
    }

    /**
     * Gets order_units
     *
     * @return \Cbdesk\Kauflandv2\Api\Model\OrderDetailsOrderUnits[]
     */
    public function getOrderUnits()
    {
        return $this->container['order_units'];
    }

    /**
     * Sets order_units
     *
     * @param \Cbdesk\Kauflandv2\Api\Model\OrderDetailsOrderUnits[] $order_units order_units
     *
     * @return $this
     */
    public function setOrderUnits($order_units)
    {
        $this->container['order_units'] = $order_units;

        return $this;
    }

    /**
     * Gets billing_address
     *
     * @return AllOfOrderDetailsBillingAddress
     */
    public function getBillingAddress()
    {
        return $this->container['billing_address'];
    }

    /**
     * Sets billing_address
     *
     * @param AllOfOrderDetailsBillingAddress $billing_address billing_address
     *
     * @return $this
     */
    public function setBillingAddress($billing_address)
    {
        $this->container['billing_address'] = $billing_address;

        return $this;
    }

    /**
     * Gets shipping_address
     *
     * @return AllOfOrderDetailsShippingAddress
     */
    public function getShippingAddress()
    {
        return $this->container['shipping_address'];
    }

    /**
     * Sets shipping_address
     *
     * @param AllOfOrderDetailsShippingAddress $shipping_address shipping_address
     *
     * @return $this
     */
    public function setShippingAddress($shipping_address)
    {
        $this->container['shipping_address'] = $shipping_address;

        return $this;
    }

    /**
     * Gets buyer
     *
     * @return AllOfOrderDetailsBuyer
     */
    public function getBuyer()
    {
        return $this->container['buyer'];
    }

    /**
     * Sets buyer
     *
     * @param AllOfOrderDetailsBuyer $buyer buyer
     *
     * @return $this
     */
    public function setBuyer($buyer)
    {
        $this->container['buyer'] = $buyer;

        return $this;
    }

    /**
     * Gets order_invoices
     *
     * @return \Cbdesk\Kauflandv2\Api\Model\OrderInvoice[]
     */
    public function getOrderInvoices()
    {
        return $this->container['order_invoices'];
    }

    /**
     * Sets order_invoices
     *
     * @param \Cbdesk\Kauflandv2\Api\Model\OrderInvoice[] $order_invoices order_invoices
     *
     * @return $this
     */
    public function setOrderInvoices($order_invoices)
    {
        $this->container['order_invoices'] = $order_invoices;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
