<?php
/**
 * TicketWithEmbedded
 *
 * PHP version 5
 *
 * @category Class
 * @package  Cbdesk\Kauflandv2\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * OpenAPI spec version: 2.9.1
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.42
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Cbdesk\Kauflandv2\Api\Model;

use \ArrayAccess;
use \Cbdesk\Kauflandv2\Api\ObjectSerializer;

/**
 * TicketWithEmbedded Class Doc Comment
 *
 * @category Class
 * @package  Cbdesk\Kauflandv2\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TicketWithEmbedded implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'TicketWithEmbedded';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id_ticket' => '\Cbdesk\Kauflandv2\Api\Model\TicketID',
'ids_order_units' => '\Cbdesk\Kauflandv2\Api\Model\LongInteger[]',
'id_buyer' => 'AllOfTicketWithEmbeddedIdBuyer',
'ts_created_iso' => '\DateTime',
'ts_updated_iso' => '\DateTime',
'status' => '\Cbdesk\Kauflandv2\Api\Model\TicketStatus',
'open_reason' => '\Cbdesk\Kauflandv2\Api\Model\TicketReason',
'topic' => 'AllOfTicketWithEmbeddedTopic',
'is_seller_responsible' => 'bool',
'fulfillment_type' => '\Cbdesk\Kauflandv2\Api\Model\FulfillmentType',
'messages' => '\Cbdesk\Kauflandv2\Api\Model\TicketMessage[]',
'order_units' => '\Cbdesk\Kauflandv2\Api\Model\OrderUnit[]',
'buyer' => 'AllOfTicketWithEmbeddedBuyer',
'product' => 'AllOfTicketWithEmbeddedProduct',
'files' => '\Cbdesk\Kauflandv2\Api\Model\TicketFile[]',
'storefront' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id_ticket' => null,
'ids_order_units' => null,
'id_buyer' => null,
'ts_created_iso' => 'date-time',
'ts_updated_iso' => 'date-time',
'status' => null,
'open_reason' => null,
'topic' => null,
'is_seller_responsible' => null,
'fulfillment_type' => null,
'messages' => null,
'order_units' => null,
'buyer' => null,
'product' => null,
'files' => null,
'storefront' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id_ticket' => 'id_ticket',
'ids_order_units' => 'ids_order_units',
'id_buyer' => 'id_buyer',
'ts_created_iso' => 'ts_created_iso',
'ts_updated_iso' => 'ts_updated_iso',
'status' => 'status',
'open_reason' => 'open_reason',
'topic' => 'topic',
'is_seller_responsible' => 'is_seller_responsible',
'fulfillment_type' => 'fulfillment_type',
'messages' => 'messages',
'order_units' => 'order_units',
'buyer' => 'buyer',
'product' => 'product',
'files' => 'files',
'storefront' => 'storefront'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id_ticket' => 'setIdTicket',
'ids_order_units' => 'setIdsOrderUnits',
'id_buyer' => 'setIdBuyer',
'ts_created_iso' => 'setTsCreatedIso',
'ts_updated_iso' => 'setTsUpdatedIso',
'status' => 'setStatus',
'open_reason' => 'setOpenReason',
'topic' => 'setTopic',
'is_seller_responsible' => 'setIsSellerResponsible',
'fulfillment_type' => 'setFulfillmentType',
'messages' => 'setMessages',
'order_units' => 'setOrderUnits',
'buyer' => 'setBuyer',
'product' => 'setProduct',
'files' => 'setFiles',
'storefront' => 'setStorefront'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id_ticket' => 'getIdTicket',
'ids_order_units' => 'getIdsOrderUnits',
'id_buyer' => 'getIdBuyer',
'ts_created_iso' => 'getTsCreatedIso',
'ts_updated_iso' => 'getTsUpdatedIso',
'status' => 'getStatus',
'open_reason' => 'getOpenReason',
'topic' => 'getTopic',
'is_seller_responsible' => 'getIsSellerResponsible',
'fulfillment_type' => 'getFulfillmentType',
'messages' => 'getMessages',
'order_units' => 'getOrderUnits',
'buyer' => 'getBuyer',
'product' => 'getProduct',
'files' => 'getFiles',
'storefront' => 'getStorefront'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id_ticket'] = isset($data['id_ticket']) ? $data['id_ticket'] : null;
        $this->container['ids_order_units'] = isset($data['ids_order_units']) ? $data['ids_order_units'] : null;
        $this->container['id_buyer'] = isset($data['id_buyer']) ? $data['id_buyer'] : null;
        $this->container['ts_created_iso'] = isset($data['ts_created_iso']) ? $data['ts_created_iso'] : null;
        $this->container['ts_updated_iso'] = isset($data['ts_updated_iso']) ? $data['ts_updated_iso'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['open_reason'] = isset($data['open_reason']) ? $data['open_reason'] : null;
        $this->container['topic'] = isset($data['topic']) ? $data['topic'] : null;
        $this->container['is_seller_responsible'] = isset($data['is_seller_responsible']) ? $data['is_seller_responsible'] : null;
        $this->container['fulfillment_type'] = isset($data['fulfillment_type']) ? $data['fulfillment_type'] : null;
        $this->container['messages'] = isset($data['messages']) ? $data['messages'] : null;
        $this->container['order_units'] = isset($data['order_units']) ? $data['order_units'] : null;
        $this->container['buyer'] = isset($data['buyer']) ? $data['buyer'] : null;
        $this->container['product'] = isset($data['product']) ? $data['product'] : null;
        $this->container['files'] = isset($data['files']) ? $data['files'] : null;
        $this->container['storefront'] = isset($data['storefront']) ? $data['storefront'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id_ticket'] === null) {
            $invalidProperties[] = "'id_ticket' can't be null";
        }
        if ($this->container['ids_order_units'] === null) {
            $invalidProperties[] = "'ids_order_units' can't be null";
        }
        if ($this->container['id_buyer'] === null) {
            $invalidProperties[] = "'id_buyer' can't be null";
        }
        if ($this->container['ts_created_iso'] === null) {
            $invalidProperties[] = "'ts_created_iso' can't be null";
        }
        if ($this->container['ts_updated_iso'] === null) {
            $invalidProperties[] = "'ts_updated_iso' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['open_reason'] === null) {
            $invalidProperties[] = "'open_reason' can't be null";
        }
        if ($this->container['topic'] === null) {
            $invalidProperties[] = "'topic' can't be null";
        }
        if ($this->container['is_seller_responsible'] === null) {
            $invalidProperties[] = "'is_seller_responsible' can't be null";
        }
        if ($this->container['fulfillment_type'] === null) {
            $invalidProperties[] = "'fulfillment_type' can't be null";
        }
        if ($this->container['messages'] === null) {
            $invalidProperties[] = "'messages' can't be null";
        }
        if ($this->container['order_units'] === null) {
            $invalidProperties[] = "'order_units' can't be null";
        }
        if ($this->container['buyer'] === null) {
            $invalidProperties[] = "'buyer' can't be null";
        }
        if ($this->container['product'] === null) {
            $invalidProperties[] = "'product' can't be null";
        }
        if ($this->container['files'] === null) {
            $invalidProperties[] = "'files' can't be null";
        }
        if ($this->container['storefront'] === null) {
            $invalidProperties[] = "'storefront' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id_ticket
     *
     * @return \Cbdesk\Kauflandv2\Api\Model\TicketID
     */
    public function getIdTicket()
    {
        return $this->container['id_ticket'];
    }

    /**
     * Sets id_ticket
     *
     * @param \Cbdesk\Kauflandv2\Api\Model\TicketID $id_ticket id_ticket
     *
     * @return $this
     */
    public function setIdTicket($id_ticket)
    {
        $this->container['id_ticket'] = $id_ticket;

        return $this;
    }

    /**
     * Gets ids_order_units
     *
     * @return \Cbdesk\Kauflandv2\Api\Model\LongInteger[]
     */
    public function getIdsOrderUnits()
    {
        return $this->container['ids_order_units'];
    }

    /**
     * Sets ids_order_units
     *
     * @param \Cbdesk\Kauflandv2\Api\Model\LongInteger[] $ids_order_units The list of order units IDs
     *
     * @return $this
     */
    public function setIdsOrderUnits($ids_order_units)
    {
        $this->container['ids_order_units'] = $ids_order_units;

        return $this;
    }

    /**
     * Gets id_buyer
     *
     * @return AllOfTicketWithEmbeddedIdBuyer
     */
    public function getIdBuyer()
    {
        return $this->container['id_buyer'];
    }

    /**
     * Sets id_buyer
     *
     * @param AllOfTicketWithEmbeddedIdBuyer $id_buyer id_buyer
     *
     * @return $this
     */
    public function setIdBuyer($id_buyer)
    {
        $this->container['id_buyer'] = $id_buyer;

        return $this;
    }

    /**
     * Gets ts_created_iso
     *
     * @return \DateTime
     */
    public function getTsCreatedIso()
    {
        return $this->container['ts_created_iso'];
    }

    /**
     * Sets ts_created_iso
     *
     * @param \DateTime $ts_created_iso Creation date of the ticket in iso 8601
     *
     * @return $this
     */
    public function setTsCreatedIso($ts_created_iso)
    {
        $this->container['ts_created_iso'] = $ts_created_iso;

        return $this;
    }

    /**
     * Gets ts_updated_iso
     *
     * @return \DateTime
     */
    public function getTsUpdatedIso()
    {
        return $this->container['ts_updated_iso'];
    }

    /**
     * Sets ts_updated_iso
     *
     * @param \DateTime $ts_updated_iso Last update on the ticket in iso 8601
     *
     * @return $this
     */
    public function setTsUpdatedIso($ts_updated_iso)
    {
        $this->container['ts_updated_iso'] = $ts_updated_iso;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Cbdesk\Kauflandv2\Api\Model\TicketStatus
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Cbdesk\Kauflandv2\Api\Model\TicketStatus $status status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets open_reason
     *
     * @return \Cbdesk\Kauflandv2\Api\Model\TicketReason
     */
    public function getOpenReason()
    {
        return $this->container['open_reason'];
    }

    /**
     * Sets open_reason
     *
     * @param \Cbdesk\Kauflandv2\Api\Model\TicketReason $open_reason open_reason
     *
     * @return $this
     */
    public function setOpenReason($open_reason)
    {
        $this->container['open_reason'] = $open_reason;

        return $this;
    }

    /**
     * Gets topic
     *
     * @return AllOfTicketWithEmbeddedTopic
     */
    public function getTopic()
    {
        return $this->container['topic'];
    }

    /**
     * Sets topic
     *
     * @param AllOfTicketWithEmbeddedTopic $topic The topic of the ticket
     *
     * @return $this
     */
    public function setTopic($topic)
    {
        $this->container['topic'] = $topic;

        return $this;
    }

    /**
     * Gets is_seller_responsible
     *
     * @return bool
     */
    public function getIsSellerResponsible()
    {
        return $this->container['is_seller_responsible'];
    }

    /**
     * Sets is_seller_responsible
     *
     * @param bool $is_seller_responsible An indicator, whether the seller needs to take action
     *
     * @return $this
     */
    public function setIsSellerResponsible($is_seller_responsible)
    {
        $this->container['is_seller_responsible'] = $is_seller_responsible;

        return $this;
    }

    /**
     * Gets fulfillment_type
     *
     * @return \Cbdesk\Kauflandv2\Api\Model\FulfillmentType
     */
    public function getFulfillmentType()
    {
        return $this->container['fulfillment_type'];
    }

    /**
     * Sets fulfillment_type
     *
     * @param \Cbdesk\Kauflandv2\Api\Model\FulfillmentType $fulfillment_type fulfillment_type
     *
     * @return $this
     */
    public function setFulfillmentType($fulfillment_type)
    {
        $this->container['fulfillment_type'] = $fulfillment_type;

        return $this;
    }

    /**
     * Gets messages
     *
     * @return \Cbdesk\Kauflandv2\Api\Model\TicketMessage[]
     */
    public function getMessages()
    {
        return $this->container['messages'];
    }

    /**
     * Sets messages
     *
     * @param \Cbdesk\Kauflandv2\Api\Model\TicketMessage[] $messages A list of the tickets' messages
     *
     * @return $this
     */
    public function setMessages($messages)
    {
        $this->container['messages'] = $messages;

        return $this;
    }

    /**
     * Gets order_units
     *
     * @return \Cbdesk\Kauflandv2\Api\Model\OrderUnit[]
     */
    public function getOrderUnits()
    {
        return $this->container['order_units'];
    }

    /**
     * Sets order_units
     *
     * @param \Cbdesk\Kauflandv2\Api\Model\OrderUnit[] $order_units A list of the order units linked to the ticket
     *
     * @return $this
     */
    public function setOrderUnits($order_units)
    {
        $this->container['order_units'] = $order_units;

        return $this;
    }

    /**
     * Gets buyer
     *
     * @return AllOfTicketWithEmbeddedBuyer
     */
    public function getBuyer()
    {
        return $this->container['buyer'];
    }

    /**
     * Sets buyer
     *
     * @param AllOfTicketWithEmbeddedBuyer $buyer The buyer of the ticket
     *
     * @return $this
     */
    public function setBuyer($buyer)
    {
        $this->container['buyer'] = $buyer;

        return $this;
    }

    /**
     * Gets product
     *
     * @return AllOfTicketWithEmbeddedProduct
     */
    public function getProduct()
    {
        return $this->container['product'];
    }

    /**
     * Sets product
     *
     * @param AllOfTicketWithEmbeddedProduct $product The product related to the ticket
     *
     * @return $this
     */
    public function setProduct($product)
    {
        $this->container['product'] = $product;

        return $this;
    }

    /**
     * Gets files
     *
     * @return \Cbdesk\Kauflandv2\Api\Model\TicketFile[]
     */
    public function getFiles()
    {
        return $this->container['files'];
    }

    /**
     * Sets files
     *
     * @param \Cbdesk\Kauflandv2\Api\Model\TicketFile[] $files Uploaded files inside the ticket
     *
     * @return $this
     */
    public function setFiles($files)
    {
        $this->container['files'] = $files;

        return $this;
    }

    /**
     * Gets storefront
     *
     * @return string
     */
    public function getStorefront()
    {
        return $this->container['storefront'];
    }

    /**
     * Sets storefront
     *
     * @param string $storefront Current storefront (country)
     *
     * @return $this
     */
    public function setStorefront($storefront)
    {
        $this->container['storefront'] = $storefront;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
