<?php
/**
 * CategoryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Kaufland\Seller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * OpenAPI spec version: 2.13.1
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Kaufland\Seller;

use PHPUnit\Framework\TestCase;

/**
 * CategoryTest Class Doc Comment
 *
 * @category    Class
 * @description Category
 * @package     Kaufland\Seller
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CategoryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Category"
     */
    public function testCategory()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "title_singular"
     */
    public function testPropertyTitleSingular()
    {
    }

    /**
     * Test attribute "title_plural"
     */
    public function testPropertyTitlePlural()
    {
    }

    /**
     * Test attribute "level"
     */
    public function testPropertyLevel()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "is_leaf"
     */
    public function testPropertyIsLeaf()
    {
    }

    /**
     * Test attribute "id_category"
     */
    public function testPropertyIdCategory()
    {
    }

    /**
     * Test attribute "id_parent_category"
     */
    public function testPropertyIdParentCategory()
    {
    }

    /**
     * Test attribute "shipping_category"
     */
    public function testPropertyShippingCategory()
    {
    }

    /**
     * Test attribute "variable_fee"
     */
    public function testPropertyVariableFee()
    {
    }

    /**
     * Test attribute "fixed_fee"
     */
    public function testPropertyFixedFee()
    {
    }

    /**
     * Test attribute "vat"
     */
    public function testPropertyVat()
    {
    }
}
