<?php
/**
 * OrderDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Cbdesk\Kauflandv2\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * OpenAPI spec version: 2.9.1
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.42
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Cbdesk\Kauflandv2\Api;

use PHPUnit\Framework\TestCase;

/**
 * OrderDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description OrderDetails
 * @package     Cbdesk\Kauflandv2\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderDetailsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OrderDetails"
     */
    public function testOrderDetails()
    {
    }

    /**
     * Test attribute "id_order"
     */
    public function testPropertyIdOrder()
    {
    }

    /**
     * Test attribute "ts_created_iso"
     */
    public function testPropertyTsCreatedIso()
    {
    }

    /**
     * Test attribute "is_marketplace_deemed_supplier"
     */
    public function testPropertyIsMarketplaceDeemedSupplier()
    {
    }

    /**
     * Test attribute "storefront"
     */
    public function testPropertyStorefront()
    {
    }

    /**
     * Test attribute "fulfillment_type"
     */
    public function testPropertyFulfillmentType()
    {
    }

    /**
     * Test attribute "order_units"
     */
    public function testPropertyOrderUnits()
    {
    }

    /**
     * Test attribute "billing_address"
     */
    public function testPropertyBillingAddress()
    {
    }

    /**
     * Test attribute "shipping_address"
     */
    public function testPropertyShippingAddress()
    {
    }

    /**
     * Test attribute "buyer"
     */
    public function testPropertyBuyer()
    {
    }

    /**
     * Test attribute "order_invoices"
     */
    public function testPropertyOrderInvoices()
    {
    }
}
