<?php
/**
 * OrderUnitTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Kaufland\Seller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * OpenAPI spec version: 2.13.1
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Kaufland\Seller;

use PHPUnit\Framework\TestCase;

/**
 * OrderUnitTest Class Doc Comment
 *
 * @category    Class
 * @description OrderUnit
 * @package     Kaufland\Seller
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderUnitTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OrderUnit"
     */
    public function testOrderUnit()
    {
    }

    /**
     * Test attribute "id_order_unit"
     */
    public function testPropertyIdOrderUnit()
    {
    }

    /**
     * Test attribute "id_order"
     */
    public function testPropertyIdOrder()
    {
    }

    /**
     * Test attribute "ts_created_iso"
     */
    public function testPropertyTsCreatedIso()
    {
    }

    /**
     * Test attribute "is_marketplace_deemed_supplier"
     */
    public function testPropertyIsMarketplaceDeemedSupplier()
    {
    }

    /**
     * Test attribute "ts_updated_iso"
     */
    public function testPropertyTsUpdatedIso()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "id_offer"
     */
    public function testPropertyIdOffer()
    {
    }

    /**
     * Test attribute "revenue_gross"
     */
    public function testPropertyRevenueGross()
    {
    }

    /**
     * Test attribute "revenue_net"
     */
    public function testPropertyRevenueNet()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "unit_condition"
     */
    public function testPropertyUnitCondition()
    {
    }

    /**
     * Test attribute "storefront"
     */
    public function testPropertyStorefront()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "delivery_time_min"
     */
    public function testPropertyDeliveryTimeMin()
    {
    }

    /**
     * Test attribute "delivery_time_max"
     */
    public function testPropertyDeliveryTimeMax()
    {
    }

    /**
     * Test attribute "delivery_time_expires_iso"
     */
    public function testPropertyDeliveryTimeExpiresIso()
    {
    }

    /**
     * Test attribute "order_received_timestamp_iso"
     */
    public function testPropertyOrderReceivedTimestampIso()
    {
    }

    /**
     * Test attribute "shipping_rate"
     */
    public function testPropertyShippingRate()
    {
    }

    /**
     * Test attribute "cancel_reason"
     */
    public function testPropertyCancelReason()
    {
    }

    /**
     * Test attribute "fulfillment_type"
     */
    public function testPropertyFulfillmentType()
    {
    }

    /**
     * Test attribute "buyer"
     */
    public function testPropertyBuyer()
    {
    }

    /**
     * Test attribute "billing_address"
     */
    public function testPropertyBillingAddress()
    {
    }

    /**
     * Test attribute "shipping_address"
     */
    public function testPropertyShippingAddress()
    {
    }

    /**
     * Test attribute "product"
     */
    public function testPropertyProduct()
    {
    }
}
