<?php
/**
 * PickSubscriptionCallbackUrlOrFallbackEmailOrEventName_Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Kaufland\Seller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * OpenAPI spec version: 2.13.1
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Kaufland\Seller;

use PHPUnit\Framework\TestCase;

/**
 * PickSubscriptionCallbackUrlOrFallbackEmailOrEventName_Test Class Doc Comment
 *
 * @category    Class
 * @description From T, pick a set of properties whose keys are in the union K
 * @package     Kaufland\Seller
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PickSubscriptionCallbackUrlOrFallbackEmailOrEventName_Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PickSubscriptionCallbackUrlOrFallbackEmailOrEventName_"
     */
    public function testPickSubscriptionCallbackUrlOrFallbackEmailOrEventName_()
    {
    }

    /**
     * Test attribute "callback_url"
     */
    public function testPropertyCallbackUrl()
    {
    }

    /**
     * Test attribute "fallback_email"
     */
    public function testPropertyFallbackEmail()
    {
    }

    /**
     * Test attribute "event_name"
     */
    public function testPropertyEventName()
    {
    }
}
