<?php
/**
 * ProductDataStatusResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Cbdesk\Kauflandv2\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * OpenAPI spec version: 2.9.1
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.42
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Cbdesk\Kauflandv2\Api;

use PHPUnit\Framework\TestCase;

/**
 * ProductDataStatusResponseTest Class Doc Comment
 *
 * @category    Class
 * @description ProductDataStatusResponse
 * @package     Cbdesk\Kauflandv2\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductDataStatusResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProductDataStatusResponse"
     */
    public function testProductDataStatusResponse()
    {
    }

    /**
     * Test attribute "product_ready"
     */
    public function testPropertyProductReady()
    {
    }

    /**
     * Test attribute "update_status"
     */
    public function testPropertyUpdateStatus()
    {
    }

    /**
     * Test attribute "id_product"
     */
    public function testPropertyIdProduct()
    {
    }

    /**
     * Test attribute "product_not_ready_reason"
     */
    public function testPropertyProductNotReadyReason()
    {
    }

    /**
     * Test attribute "update_fail_reason"
     */
    public function testPropertyUpdateFailReason()
    {
    }

    /**
     * Test attribute "attribute_values"
     */
    public function testPropertyAttributeValues()
    {
    }

    /**
     * Test attribute "missing_attributes"
     */
    public function testPropertyMissingAttributes()
    {
    }

    /**
     * Test attribute "min_one_missing_attributes"
     */
    public function testPropertyMinOneMissingAttributes()
    {
    }
}
