<?php
/**
 * ProductTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Kaufland\Seller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * OpenAPI spec version: 2.13.1
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Kaufland\Seller;

use PHPUnit\Framework\TestCase;

/**
 * ProductTest Class Doc Comment
 *
 * @category    Class
 * @description Product
 * @package     Kaufland\Seller
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Product"
     */
    public function testProduct()
    {
    }

    /**
     * Test attribute "id_product"
     */
    public function testPropertyIdProduct()
    {
    }

    /**
     * Test attribute "storefront"
     */
    public function testPropertyStorefront()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "eans"
     */
    public function testPropertyEans()
    {
    }

    /**
     * Test attribute "id_category"
     */
    public function testPropertyIdCategory()
    {
    }

    /**
     * Test attribute "main_picture"
     */
    public function testPropertyMainPicture()
    {
    }

    /**
     * Test attribute "manufacturer"
     */
    public function testPropertyManufacturer()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "age_rating"
     */
    public function testPropertyAgeRating()
    {
    }

    /**
     * Test attribute "is_valid"
     */
    public function testPropertyIsValid()
    {
    }

    /**
     * Test attribute "dangerous_goods_li_shipping"
     */
    public function testPropertyDangerousGoodsLiShipping()
    {
    }

    /**
     * Test attribute "danger_label_9_a"
     */
    public function testPropertyDangerLabel9A()
    {
    }
}
