<?php
/**
 * ReturnUnitDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Cbdesk\Kauflandv2\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * OpenAPI spec version: 2.9.1
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.42
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Cbdesk\Kauflandv2\Api;

use PHPUnit\Framework\TestCase;

/**
 * ReturnUnitDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description ReturnUnitDetails
 * @package     Cbdesk\Kauflandv2\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReturnUnitDetailsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ReturnUnitDetails"
     */
    public function testReturnUnitDetails()
    {
    }

    /**
     * Test attribute "id_return_unit"
     */
    public function testPropertyIdReturnUnit()
    {
    }

    /**
     * Test attribute "id_return"
     */
    public function testPropertyIdReturn()
    {
    }

    /**
     * Test attribute "id_order_unit"
     */
    public function testPropertyIdOrderUnit()
    {
    }

    /**
     * Test attribute "ts_created_iso"
     */
    public function testPropertyTsCreatedIso()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "reason"
     */
    public function testPropertyReason()
    {
    }

    /**
     * Test attribute "storefront"
     */
    public function testPropertyStorefront()
    {
    }

    /**
     * Test attribute "fulfillment_type"
     */
    public function testPropertyFulfillmentType()
    {
    }

    /**
     * Test attribute "return"
     */
    public function testPropertyReturn()
    {
    }

    /**
     * Test attribute "tickets"
     */
    public function testPropertyTickets()
    {
    }

    /**
     * Test attribute "order_unit"
     */
    public function testPropertyOrderUnit()
    {
    }
}
