<?php
/**
 * ShippingGroupOptionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Cbdesk\Kauflandv2\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * OpenAPI spec version: 2.9.1
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.42
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Cbdesk\Kauflandv2\Api;

use PHPUnit\Framework\TestCase;

/**
 * ShippingGroupOptionTest Class Doc Comment
 *
 * @category    Class
 * @description ShippingGroupOption
 * @package     Cbdesk\Kauflandv2\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShippingGroupOptionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ShippingGroupOption"
     */
    public function testShippingGroupOption()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "cost_first"
     */
    public function testPropertyCostFirst()
    {
    }

    /**
     * Test attribute "cost_next"
     */
    public function testPropertyCostNext()
    {
    }

    /**
     * Test attribute "cost_max"
     */
    public function testPropertyCostMax()
    {
    }

    /**
     * Test attribute "cost_free"
     */
    public function testPropertyCostFree()
    {
    }

    /**
     * Test attribute "cut_off_time"
     */
    public function testPropertyCutOffTime()
    {
    }

    /**
     * Test attribute "transport_time_min"
     */
    public function testPropertyTransportTimeMin()
    {
    }

    /**
     * Test attribute "transport_time_max"
     */
    public function testPropertyTransportTimeMax()
    {
    }
}
