<?php
/**
 * UnitRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Kaufland\Seller
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * OpenAPI spec version: 2.13.1
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.54
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Kaufland\Seller;

use PHPUnit\Framework\TestCase;

/**
 * UnitRequestTest Class Doc Comment
 *
 * @category    Class
 * @description UnitRequest
 * @package     Kaufland\Seller
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UnitRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UnitRequest"
     */
    public function testUnitRequest()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "handling_time"
     */
    public function testPropertyHandlingTime()
    {
    }

    /**
     * Test attribute "listing_price"
     */
    public function testPropertyListingPrice()
    {
    }

    /**
     * Test attribute "minimum_price"
     */
    public function testPropertyMinimumPrice()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "id_shipping_group"
     */
    public function testPropertyIdShippingGroup()
    {
    }

    /**
     * Test attribute "id_warehouse"
     */
    public function testPropertyIdWarehouse()
    {
    }

    /**
     * Test attribute "ean"
     */
    public function testPropertyEan()
    {
    }

    /**
     * Test attribute "id_product"
     */
    public function testPropertyIdProduct()
    {
    }

    /**
     * Test attribute "id_offer"
     */
    public function testPropertyIdOffer()
    {
    }

    /**
     * Test attribute "condition"
     */
    public function testPropertyCondition()
    {
    }
}
