<?php
/**
 * ReturnUnitsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Cbdesk\Kauflandv2\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * OpenAPI spec version: 2.9.1
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.42
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Cbdesk\Kauflandv2\Api;

use Cbdesk\Kauflandv2\Api\Configuration;
use Cbdesk\Kauflandv2\Api\ApiException;
use Cbdesk\Kauflandv2\Api\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ReturnUnitsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Cbdesk\Kauflandv2\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReturnUnitsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for acceptReturnUnit
     *
     * Accept a return unit.
     *
     */
    public function testAcceptReturnUnit()
    {
    }

    /**
     * Test case for clarifyReturnUnit
     *
     * Clarify a return unit.
     *
     */
    public function testClarifyReturnUnit()
    {
    }

    /**
     * Test case for getReturnUnit
     *
     * Get a return unit by ID.
     *
     */
    public function testGetReturnUnit()
    {
    }

    /**
     * Test case for getReturnUnits
     *
     * Get a list of return units.
     *
     */
    public function testGetReturnUnits()
    {
    }

    /**
     * Test case for rejectReturnUnit
     *
     * Reject a return unit.
     *
     */
    public function testRejectReturnUnit()
    {
    }

    /**
     * Test case for repairReturnUnit
     *
     * Repair a return unit.
     *
     */
    public function testRepairReturnUnit()
    {
    }
}
