<?php
/**
 * SubscriptionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Cbdesk\Kauflandv2\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kaufland.de Seller API v2
 *
 * This is the Kaufland.de Seller API v2. You can find more information on [https://sellerapi.kaufland.com/](https://sellerapi.kaufland.com/)
 *
 * OpenAPI spec version: 2.9.1
 * Contact: seller-api-support@kaufland-online.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.42
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Cbdesk\Kauflandv2\Api;

use Cbdesk\Kauflandv2\Api\Configuration;
use Cbdesk\Kauflandv2\Api\ApiException;
use Cbdesk\Kauflandv2\Api\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SubscriptionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Cbdesk\Kauflandv2\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addSubscription
     *
     * Subscribe for event.
     *
     */
    public function testAddSubscription()
    {
    }

    /**
     * Test case for deleteSubscription
     *
     * Unsubscribe from event.
     *
     */
    public function testDeleteSubscription()
    {
    }

    /**
     * Test case for getSubscription
     *
     * Get a push notification subscription by ID.
     *
     */
    public function testGetSubscription()
    {
    }

    /**
     * Test case for getSubscriptions
     *
     * Get a list of your push notification subscriptions.
     *
     */
    public function testGetSubscriptions()
    {
    }

    /**
     * Test case for updateSubscription
     *
     * Update subscription.
     *
     */
    public function testUpdateSubscription()
    {
    }
}
